export const languagesOptions = [
  "English",
  "English (Australia)",
  "English (Canada)",
  "English (India)",
  "English (New Zealand)",
  "English (South Africa)",
  "English (United Kingdom)",
  "English (United States)",
  "Central Kurdish - کوردی (دەستنوسی عەرەبی)",
  "Chinese - 中文",
  "Chinese (Hong Kong) - 中文（香港）",
  "Chinese (Simplified) - 中文（简体）",
  "Chinese (Traditional) - 中文（繁體）",
  "French - français",
  "French (Canada) - français (Canada)",
  "French (France) - français (France)",
  "French (Switzerland) - français (Suisse)",
  "German (Austria) - Deutsch (Österreich)",
  "Hebrew - עברית",
  "Hindi - हिन्दी",
  "Italian (Italy) - italiano (Italia)",
  "Japanese - 日本語",
  "Lao - ລາວ",
  "Latin",
  "Mongolian - монгол",
  "Portuguese - português",
  "Portuguese (Brazil) - português (Brasil)",
  "Portuguese (Portugal) - português (Portugal)",
  "Spanish - español",
  "Spanish (Mexico) - español (México)",
  "Spanish (Spain) - español (España)",
  "Spanish (United States) - español (Estados Unidos)",
  "Swahili - Kiswahili",
  "Xhosa",
  "Zulu - isiZulu",
];

export const surveyData = {
  heighlights: {
    lorem1: {
      min: 0,
      max: 1000,
      value: 841,
    },
    lorem2: {
      min: 0,
      max: 1000,
      value: 642,
    },
    lorem3: {
      min: 0,
      max: 1000,
      value: 361,
    },
    lorem4: {
      min: 0,
      max: 1000,
      value: 242,
    },
  },
  statuses: [
    {
      type: "Opened",
      number: 834,
      direction: "positive",
      percentage: 20,
    },
    {
      type: "Cancelled",
      number: 234,
      direction: "positive",
      percentage: 15,
    },
    {
      type: "Incomplete",
      number: 642,
      direction: "positive",
      percentage: 20,
    },
    {
      type: "New Customers",
      number: 453,
      direction: "negetive",
      percentage: 15,
    },
    {
      type: "Opened",
      number: 834,
      direction: "positive",
      percentage: 20,
    },
    {
      type: "Old Survey",
      number: 678,
      direction: "positive",
      percentage: 20,
    },
  ],
};

export const PerspectivePredictiveAnalysisCardData = {
  min: 0,
  max: 0,
  values: [200, 250, 110, 350, 200, 300, 100, 300, 350, 200, 200, 300],
  labels: [
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "May",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Oct",
    "Nov",
    "Dec",
  ],
};

export const CasualAnalysisData = [
  { name: "Lorem", value: 16.66 },
  { name: "Lorem", value: 16.66 },
  { name: "Lorem", value: 16.66 },
  { name: "Lorem", value: 16.66 },
  { name: "Lorem", value: 16.66 },
  { name: "Lorem", value: 16.66 },
];
